Remove exampleClusterBuilder.create property
cloudfoundry/korifi pull request #1772
Opened 2022-10-11 14:36 UTC by kieron-dev

## Is there a related GitHub Issue?
#1578

## What is this change about?
Instead of putting `exampleClusterBuilder.create: true`, we now just leave `clusterBuilderName` empty in order to make helm create the example cluster builder configuration.

## Does this PR introduce a breaking change?
No

## Acceptance Steps

## Tag your pair, your PM, and/or team

## Things to remember

2022-10-11 15:14 UTC, gcapizzi requested changes

2022-10-11 15:18 UTC, kieron-dev commented on helm/README.values.md
>      kpackBuilderRegistry: registry-org/kpack-builder-repo-name
There's already another registry in kpack-image-builder though - the packageRegistry.

How about `builderRegistry`?

2022-10-11 15:25 UTC, gcapizzi commented on helm/README.values.md
>      kpackBuilderRegistry: registry-org/kpack-builder-repo-name
that's confusing - I see we use `packageRegistry` to set `kpackImageTag`, which should be for droplets?

2022-10-11 15:29 UTC, kieron-dev commented on helm/README.values.md
>      kpackBuilderRegistry: registry-org/kpack-builder-repo-name
OK - that needs changing too.

2022-10-11 15:31 UTC, gcapizzi commented on helm/README.values.md
>      kpackBuilderRegistry: registry-org/kpack-builder-repo-name
but you're right, there's still two "registries", one is the builder image tag, and the other is the prefix for droplet tags

2022-10-13 10:16 UTC, gcapizzi approved these changes

2022-10-13 10:17 UTC, merged