Remove the finaizer from CFServiceInstance
cloudfoundry/korifi pull request #1877
Opened 2022-11-08 11:39 UTC by danail-branekov

## Is there a related GitHub Issue?
https://github.com/cloudfoundry/korifi/issues/1876

## What is this change about?
The finalizer has been replaced by setting owner reference from the service to the
service binding in the service binding repository

## Does this PR introduce a breaking change?
No

## Acceptance Steps
N/A

## Tag your pair, your PM, and/or team
@kieron-dev

2022-11-08 11:55 UTC, georgethebeatle commented on tools/k8s/owner_test.go
> +var _ = FDescribe("Owner", func() {
Opps :)

2022-11-08 12:00 UTC, kieron-dev requested changes

2022-11-08 16:33 UTC, danail-branekov commented
We have realised that with this change a service binding has two owners - the app and the service. If one of them is deleted, the binding remains behind. In order to be deleted automatically, both the app AND the service have to be deleted. This is something we don't really want

2022-11-10 14:04 UTC, danail-branekov commented
This PR is no longer needed. The issue addressed with https://github.com/cloudfoundry/korifi/pull/1882

2022-11-10 14:04 UTC, closed without merging