Write `Succeeded` condition only after adding droplet info into `BuildWorkload` status
cloudfoundry/korifi pull request #3497
Opened 2024-09-30 17:22 UTC by pbusko

## Is there a related GitHub Issue?

no

## What is this change about?

If an error is thrown during the [generation of droplet status](https://github.com/cloudfoundry/korifi/blob/7b38428e46429002e303e8cbd428422ce2a859d3/kpack-image-builder/controllers/buildworkload_controller.go#L268-L282), the `BuildWorkload` object ends up in a deadlock situation, where each subsequent reconciliation loop exits early and no droplet info is written.

## Does this PR introduce a breaking change?

no

## Acceptance Steps

## Tag your pair, your PM, and/or team

2024-10-02 13:51 UTC, danail-branekov commented
Hey @pbusko 

Thanks for the PR. Would be willing to also backfill a test that verifies the fix? Looks good otherwise

2024-10-04 12:04 UTC, pbusko commented
> Hey @pbusko
> 
> Thanks for the PR. Would you be willing to also backfill a test that verifies the fix? Looks good otherwise

a test has been added

2024-10-08 14:44 UTC, danail-branekov approved these changes

2024-10-08 16:53 UTC, danail-branekov requested changes
Minor comments on the test, looks good otherwise

2024-10-08 16:53 UTC, danail-branekov commented on kpack-image-builder/controllers/buildworkload_controller_test.go
> +			Expect(k8s.Patch(ctx, adminClient, build, func() {
Patching the build status could take place in the `BeforeEach` instead of `JustBeforeEach` - this makes the setup simpler to read

2024-10-08 16:53 UTC, danail-branekov commented on kpack-image-builder/controllers/buildworkload_controller_test.go
> +				g.Expect(mustHaveCondition(g, buildWorkload.Status.Conditions, "Succeeded").Status).To(Equal(metav1.ConditionUnknown))
The assertions below could be improved as follows:

```
				g.Expect(buildWorkload.Status.Conditions).To(ContainElements(
					SatisfyAll(
						matchers.HasType(Equal(korifiv1alpha1.SucceededConditionType)),
						matchers.HasStatus(Not(Equal(metav1.ConditionTrue))),
					),
					SatisfyAll(
						matchers.HasType(Equal(korifiv1alpha1.StatusConditionReady)),
						matchers.HasStatus(Equal(metav1.ConditionFalse)),
						matchers.HasMessage(ContainSubstring("fake error")),
					),
				))
```

2024-10-09 06:42 UTC, pbusko commented
> apply review suggestions

https://github.com/cloudfoundry/korifi/pull/3497/commits/4ea98ebb546c401012d0051ce562581b9833100c

2024-10-11 14:24 UTC, danail-branekov approved these changes

2024-10-11 14:25 UTC, merged